


<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> | </title>

        <link rel="stylesheet" href="/css/style.css">
        <link rel="stylesheet" href="/css/highlight.css">
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'>

        <!-- Font Awesome -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <!-- Fetch JQuery from CDN but have a local fallback -->
        <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script>
            if (typeof jQuery == 'undefined') {
                document.write(unescape("%3Cscript src='/jquery.js'%3E%3C/script%3E"));
            }
        </script>
    </head>
    <body>
        <!-- Set the theme before any content is loaded, prevents flash -->
        <script>
            var theme = localStorage.getItem('theme');
            if (theme == null) { theme = 'light'; }
            $('body').removeClass().addClass(theme);
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script>
            var sidebar = localStorage.getItem('sidebar');
            if (sidebar === "hidden") { $("html").addClass("sidebar-hidden") }
            else if (sidebar === "visible") { $("html").addClass("sidebar-visible") }
        </script>

        <div id="sidebar" class="sidebar">
            <ul class="chapter">

              
              <li>
                <a href="#about-this-book.html"> About This Book</a>
              </li>
              
              <li>
                <a href="#language.html"> Language Structure</a>
              </li>
              
              <li>
                <a href="#builtin.html"> Built-in Classes</a>
              </li>
              
              <li>
                <a href="#stdlib.html"> Standard Library</a>
              </li>
              
              <li>
                <a href="#advanced-topics.html"> Advanced Topics</a>
              </li>
              

            </ul>
        </div>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                <div id="menu-bar" class="menu-bar">
                    <div class="left-buttons">
                        <i id="sidebar-toggle" class="fa fa-bars"></i>
                        <i id="theme-toggle" class="fa fa-paint-brush"></i>
                    </div>

                    <h1 class="menu-title"></h1>

                    <div class="right-buttons">
                        <i id="print-button" class="fa fa-print" title="Print this book"></i>
                    </div>
                </div>

                 <h1 id="built-in-exception-classes">Built-in Exception Classes</h1>

<h2 id="nomemoryerror">NoMemoryError</h2>

<p>Raised when memory allocation fails.</p>

<p><a href="http://ruby-doc.org/core-2.5.0/NoMemoryError.html">NoMemoryError
Reference</a></p>

<h2 id="scripterror">ScriptError</h2>

<p>ScriptError is the superclass for errors raised when a script can not be
executed because of a <code class="highlighter-rouge">LoadError</code>, <code class="highlighter-rouge">NotImplementedError</code> or a
<code class="highlighter-rouge">SyntaxError</code>. Note these type of <code class="highlighter-rouge">ScriptErrors</code> are not <code class="highlighter-rouge">StandardError</code>
and will not be rescued unless it is specified explicitly (or its
ancestor <code class="highlighter-rouge">Exception</code>).</p>

<p><a href="http://ruby-doc.org/core-2.5.0/ScriptError.html">ScriptError Reference</a></p>

<h3 id="loaderror">LoadError</h3>

<p>Raised when a file required (a Ruby script, extension library, â€¦)
fails to load.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nb">require</span> <span class="s1">'this/file/does/not/exist'</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">LoadError</span><span class="p">:</span> <span class="n">no</span> <span class="n">such</span> <span class="n">file</span> <span class="n">to</span> <span class="nb">load</span> <span class="o">--</span> <span class="n">this</span><span class="o">/</span><span class="n">file</span><span class="o">/</span><span class="n">does</span><span class="o">/</span><span class="n">not</span><span class="o">/</span><span class="n">exist</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/LoadError.html">LoadError Reference</a></p>

<h3 id="notimplementederror">NotImplementedError</h3>

<p>Raised when a feature is not implemented on the current platform. For
example, methods depending on the <code class="highlighter-rouge">fsync</code> or <code class="highlighter-rouge">fork</code> system calls may
raise this exception if the underlying operating system or Ruby runtime
does not support them.</p>

<p>Note that if <code class="highlighter-rouge">fork</code> raises a <code class="highlighter-rouge">NotImplementedError</code>, then
<code class="highlighter-rouge">respond_to?(:fork)</code> returns <code class="highlighter-rouge">false</code>.</p>

<p><a href="http://ruby-doc.org/core-2.5.0/NotImplementedError.html">NotImplementedError
Reference</a></p>

<h3 id="syntaxerror">SyntaxError</h3>

<p>Raised when encountering Ruby code with an invalid syntax.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nb">eval</span><span class="p">(</span><span class="s2">"1+1=2"</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">SyntaxError</span><span class="p">:</span> <span class="p">(</span><span class="nb">eval</span><span class="p">):</span><span class="mi">1</span><span class="p">:</span> <span class="n">syntax</span> <span class="n">error</span><span class="p">,</span> <span class="n">unexpected</span> <span class="s1">'='</span><span class="p">,</span> <span class="n">expecting</span> <span class="vg">$end</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/SyntaxError.html">SyntaxError Reference</a></p>

<h2 id="securityerror">SecurityError</h2>

<p>Raised when attempting a potential unsafe operation, typically when the
$SAFE level is raised above 0.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">foo</span> <span class="o">=</span> <span class="s2">"bar"</span>
<span class="nb">proc</span> <span class="o">=</span> <span class="no">Proc</span><span class="p">.</span><span class="nf">new</span> <span class="k">do</span>
  <span class="vg">$SAFE</span> <span class="o">=</span> <span class="mi">3</span>
  <span class="n">foo</span><span class="p">.</span><span class="nf">untaint</span>
<span class="k">end</span>
<span class="nb">proc</span><span class="p">.</span><span class="nf">call</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">SecurityError</span><span class="p">:</span> <span class="no">Insecure</span><span class="p">:</span> <span class="no">Insecure</span> <span class="n">operation</span> <span class="sb">`untaint`</span> <span class="n">at</span> <span class="n">level</span> <span class="mi">3</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/SecurityError.html">SecurityError
Reference</a></p>

<h2 id="signalexception">SignalException</h2>

<p>Raised when a signal is received.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">begin</span>
  <span class="no">Process</span><span class="p">.</span><span class="nf">kill</span><span class="p">(</span><span class="s1">'HUP'</span><span class="p">,</span><span class="no">Process</span><span class="p">.</span><span class="nf">pid</span><span class="p">)</span>
  <span class="nb">sleep</span> <span class="c1"># wait for receiver to handle signal sent by Process.kill</span>
<span class="k">rescue</span> <span class="no">SignalException</span> <span class="o">=&gt;</span> <span class="n">e</span>
  <span class="nb">puts</span> <span class="s2">"received Exception </span><span class="si">#{</span><span class="n">e</span><span class="si">}</span><span class="s2">"</span>
<span class="k">end</span>
</code></pre></div></div>

<p><em>produces:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">received</span> <span class="no">Exception</span> <span class="no">SIGHUP</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/SignalException.html">SignalException
Reference</a></p>

<h3 id="interrupt">Interrupt</h3>

<p>Raised with the interrupt signal is received, typically because the user
pressed on Control-C (on most posix platforms). As such, it is a
subclass of <code class="highlighter-rouge">SignalException</code>.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">begin</span>
  <span class="nb">puts</span> <span class="s2">"Press ctrl-C when you get bored"</span>
  <span class="kp">loop</span> <span class="p">{}</span>
<span class="k">rescue</span> <span class="no">Interrupt</span> <span class="o">=&gt;</span> <span class="n">e</span>
  <span class="nb">puts</span> <span class="s2">"Note: You will typically use Signal.trap instead."</span>
<span class="k">end</span>
</code></pre></div></div>

<p><em>produces:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Press</span> <span class="n">ctrl</span><span class="o">-</span><span class="no">C</span> <span class="k">when</span> <span class="n">you</span> <span class="n">get</span> <span class="n">bored</span>
</code></pre></div></div>

<p><em>then waits until it is interrupted with Control-C and then prints:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Note</span><span class="p">:</span> <span class="no">You</span> <span class="n">will</span> <span class="n">typically</span> <span class="n">use</span> <span class="no">Signal</span><span class="p">.</span><span class="nf">trap</span> <span class="n">instead</span><span class="o">.</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/Interrupt.html">Interrupt Reference</a></p>

<h2 id="standarderror">StandardError</h2>

<p>The most standard error types are subclasses of StandardError. A rescue
clause without an explicit Exception class will rescue all
StandardErrors (and only those).</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">foo</span>
  <span class="k">raise</span> <span class="s2">"Oups"</span>
<span class="k">end</span>
<span class="n">foo</span> <span class="k">rescue</span> <span class="s2">"Hello"</span>   <span class="c1">#=&gt; "Hello"</span>
</code></pre></div></div>

<p>On the other hand:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nb">require</span> <span class="s1">'does/not/exist'</span> <span class="k">rescue</span> <span class="s2">"Hi"</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">LoadError</span><span class="p">:</span> <span class="n">no</span> <span class="n">such</span> <span class="n">file</span> <span class="n">to</span> <span class="nb">load</span> <span class="o">--</span> <span class="n">does</span><span class="o">/</span><span class="n">not</span><span class="o">/</span><span class="n">exist</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/StandardError.html">StandardError
Reference</a></p>

<h3 id="argumenterror">ArgumentError</h3>

<p>Raised when the arguments are wrong and there isnâ€™t a more specific
Exception class.</p>

<p>Ex: passing the wrong number of arguments</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">].</span><span class="nf">first</span><span class="p">(</span><span class="mi">4</span><span class="p">,</span> <span class="mi">5</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">ArgumentError</span><span class="p">:</span> <span class="n">wrong</span> <span class="n">number</span> <span class="n">of</span> <span class="n">arguments</span> <span class="p">(</span><span class="n">given</span> <span class="mi">2</span><span class="p">,</span> <span class="n">expected</span> <span class="mi">1</span><span class="p">)</span>
</code></pre></div></div>

<p>Ex: passing an argument that is not acceptable:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">].</span><span class="nf">first</span><span class="p">(</span><span class="o">-</span><span class="mi">4</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">ArgumentError</span><span class="p">:</span> <span class="n">negative</span> <span class="n">array</span> <span class="n">size</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/ArgumentError.html">ArgumentError
Reference</a></p>

<h4 id="uncaughtthrowerror">UncaughtThrowError</h4>

<p>Raised when <code class="highlighter-rouge">throw</code> is called with a <em>tag</em> which does not have
corresponding <code class="highlighter-rouge">catch</code> block.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kp">throw</span> <span class="s2">"foo"</span><span class="p">,</span> <span class="s2">"bar"</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">UncaughtThrowError</span><span class="p">:</span> <span class="n">uncaught</span> <span class="kp">throw</span> <span class="s2">"foo"</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/UncaughtThrowError.html">UncaughtThrowError
Reference</a></p>

<h3 id="encodingerror">EncodingError</h3>

<p>EncodingError is the base class for encoding errors.</p>

<p><a href="http://ruby-doc.org/core-2.5.0/EncodingError.html">EncodingError
Reference</a></p>

<h3 id="fibererror">FiberError</h3>

<p>Raised when an invalid operation is attempted on a Fiber, in particular
when attempting to call/resume a dead fiber, attempting to yield from
the root fiber, or calling a fiber across threads.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">fiber</span> <span class="o">=</span> <span class="no">Fiber</span><span class="p">.</span><span class="nf">new</span><span class="p">{}</span>
<span class="n">fiber</span><span class="p">.</span><span class="nf">resume</span> <span class="c1">#=&gt; nil</span>
<span class="n">fiber</span><span class="p">.</span><span class="nf">resume</span> <span class="c1">#=&gt; FiberError: dead fiber called</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/FiberError.html">FiberError Reference</a></p>

<h3 id="ioerror">IOError</h3>

<p>Raised when an IO operation fails.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">File</span><span class="p">.</span><span class="nf">open</span><span class="p">(</span><span class="s2">"/etc/hosts"</span><span class="p">)</span> <span class="p">{</span><span class="o">|</span><span class="n">f</span><span class="o">|</span> <span class="n">f</span> <span class="o">&lt;&lt;</span> <span class="s2">"example"</span><span class="p">}</span>
  <span class="c1">#=&gt; IOError: not opened for writing</span>

<span class="no">File</span><span class="p">.</span><span class="nf">open</span><span class="p">(</span><span class="s2">"/etc/hosts"</span><span class="p">)</span> <span class="p">{</span><span class="o">|</span><span class="n">f</span><span class="o">|</span> <span class="n">f</span><span class="p">.</span><span class="nf">close</span><span class="p">;</span> <span class="n">f</span><span class="p">.</span><span class="nf">read</span> <span class="p">}</span>
  <span class="c1">#=&gt; IOError: closed stream</span>
</code></pre></div></div>

<p>Note that some IO failures raise `SystemCallErrorâ€™s and these are not
subclasses of IOError:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">File</span><span class="p">.</span><span class="nf">open</span><span class="p">(</span><span class="s2">"does/not/exist"</span><span class="p">)</span>
  <span class="c1">#=&gt; Errno::ENOENT: No such file or directory - does/not/exist</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/IOError.html">IOError Reference</a></p>

<h4 id="eoferror">EOFError</h4>

<p>Raised by some IO operations when reaching the end of file. Many IO
methods exist in two forms,</p>

<p>one that returns <code class="highlighter-rouge">nil</code> when the end of file is reached, the other raises
<code class="highlighter-rouge">EOFError</code>.</p>

<p><code class="highlighter-rouge">EOFError</code> is a subclass of <code class="highlighter-rouge">IOError</code>.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">file</span> <span class="o">=</span> <span class="no">File</span><span class="p">.</span><span class="nf">open</span><span class="p">(</span><span class="s2">"/etc/hosts"</span><span class="p">)</span>
<span class="n">file</span><span class="p">.</span><span class="nf">read</span>
<span class="n">file</span><span class="p">.</span><span class="nf">gets</span>     <span class="c1">#=&gt; nil</span>
<span class="n">file</span><span class="p">.</span><span class="nf">readline</span> <span class="c1">#=&gt; EOFError: end of file reached</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/EOFError.html">EOFError Reference</a></p>

<h3 id="indexerror">IndexError</h3>

<p>Raised when the given index is invalid.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">a</span> <span class="o">=</span> <span class="p">[</span><span class="ss">:foo</span><span class="p">,</span> <span class="ss">:bar</span><span class="p">]</span>
<span class="n">a</span><span class="p">.</span><span class="nf">fetch</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>   <span class="c1">#=&gt; :foo</span>
<span class="n">a</span><span class="p">[</span><span class="mi">4</span><span class="p">]</span>         <span class="c1">#=&gt; nil</span>
<span class="n">a</span><span class="p">.</span><span class="nf">fetch</span><span class="p">(</span><span class="mi">4</span><span class="p">)</span>   <span class="c1">#=&gt; IndexError: index 4 outside of array bounds: -2...2</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/IndexError.html">IndexError Reference</a></p>

<h4 id="keyerror">KeyError</h4>

<p>Raised when the specified key is not found. It is a subclass of
IndexError.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">h</span> <span class="o">=</span> <span class="p">{</span><span class="s2">"foo"</span> <span class="o">=&gt;</span> <span class="ss">:bar</span><span class="p">}</span>
<span class="n">h</span><span class="p">.</span><span class="nf">fetch</span><span class="p">(</span><span class="s2">"foo"</span><span class="p">)</span> <span class="c1">#=&gt; :bar</span>
<span class="n">h</span><span class="p">.</span><span class="nf">fetch</span><span class="p">(</span><span class="s2">"baz"</span><span class="p">)</span> <span class="c1">#=&gt; KeyError: key not found: "baz"</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/KeyError.html">KeyError Reference</a></p>

<h4 id="stopiteration">StopIteration</h4>

<p>Raised to stop the iteration, in particular by <code class="highlighter-rouge">Enumerator#next</code>. It is
rescued by <code class="highlighter-rouge">Kernel#loop</code>.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kp">loop</span> <span class="k">do</span>
  <span class="nb">puts</span> <span class="s2">"Hello"</span>
  <span class="k">raise</span> <span class="no">StopIteration</span>
  <span class="nb">puts</span> <span class="s2">"World"</span>
<span class="k">end</span>
<span class="nb">puts</span> <span class="s2">"Done!"</span>
</code></pre></div></div>

<p><em>produces:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Hello</span>
<span class="no">Done</span><span class="o">!</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/StopIteration.html">StopIteration
Reference</a></p>

<h3 id="localjumperror">LocalJumpError</h3>

<p>Raised when Ruby canâ€™t yield as requested.</p>

<p>A typical scenario is attempting to yield when no block is given:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">call_block</span>
  <span class="k">yield</span> <span class="mi">42</span>
<span class="k">end</span>
<span class="n">call_block</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">LocalJumpError</span><span class="p">:</span> <span class="n">no</span> <span class="n">block</span> <span class="n">given</span> <span class="p">(</span><span class="k">yield</span><span class="p">)</span>
</code></pre></div></div>

<p>A more subtle example:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">get_me_a_return</span>
  <span class="no">Proc</span><span class="p">.</span><span class="nf">new</span> <span class="p">{</span> <span class="k">return</span> <span class="mi">42</span> <span class="p">}</span>
<span class="k">end</span>
<span class="n">get_me_a_return</span><span class="p">.</span><span class="nf">call</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">LocalJumpError</span><span class="p">:</span> <span class="n">unexpected</span> <span class="k">return</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/LocalJumpError.html">LocalJumpError
Reference</a></p>

<h3 id="nameerror">NameError</h3>

<p>Raised when a given name is invalid or undefined.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nb">puts</span> <span class="n">foo</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">NameError</span><span class="p">:</span> <span class="n">undefined</span> <span class="n">local</span> <span class="n">variable</span> <span class="n">or</span> <span class="nb">method</span> <span class="sb">`foo`</span> <span class="k">for</span> <span class="n">main</span><span class="ss">:Object</span>
</code></pre></div></div>

<p>Since constant names must start with a capital:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Integer</span><span class="p">.</span><span class="nf">const_set</span> <span class="ss">:answer</span><span class="p">,</span> <span class="mi">42</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">NameError</span><span class="p">:</span> <span class="n">wrong</span> <span class="n">constant</span> <span class="nb">name</span> <span class="n">answer</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/NameError.html">NameError Reference</a></p>

<h4 id="nomethoderror">NoMethodError</h4>

<p>Raised when a method is called on a receiver which doesnâ€™t have it
defined and also fails to respond with <code class="highlighter-rouge">method_missing</code>.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="s2">"hello"</span><span class="p">.</span><span class="nf">to_ary</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">NoMethodError</span><span class="p">:</span> <span class="n">undefined</span> <span class="nb">method</span> <span class="sb">`to_ary`</span> <span class="k">for</span> <span class="s2">"hello"</span><span class="ss">:String</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/NoMethodError.html">NoMethodError
Reference</a></p>

<h3 id="rangeerror">RangeError</h3>

<p>Raised when a given numerical value is out of range.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">].</span><span class="nf">drop</span><span class="p">(</span><span class="mi">1</span> <span class="o">&lt;&lt;</span> <span class="mi">100</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">RangeError</span><span class="p">:</span> <span class="n">bignum</span> <span class="n">too</span> <span class="n">big</span> <span class="n">to</span> <span class="n">convert</span> <span class="n">into</span> <span class="sb">`long`</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/RangeError.html">RangeError Reference</a></p>

<h4 id="floatdomainerror">FloatDomainError</h4>

<p>Raised when attempting to convert special float values (in particular
<code class="highlighter-rouge">Infinity</code> or <code class="highlighter-rouge">NaN</code>) to numerical classes which donâ€™t support them.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Float</span><span class="o">::</span><span class="no">INFINITY</span><span class="p">.</span><span class="nf">to_r</span>   <span class="c1">#=&gt; FloatDomainError: Infinity</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/FloatDomainError.html">FloatDomainError
Reference</a></p>

<h3 id="regexperror">RegexpError</h3>

<p>Raised when given an invalid regexp expression.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Regexp</span><span class="p">.</span><span class="nf">new</span><span class="p">(</span><span class="s2">"?"</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">RegexpError</span><span class="p">:</span> <span class="n">target</span> <span class="n">of</span> <span class="n">repeat</span> <span class="n">operator</span> <span class="n">is</span> <span class="n">not</span> <span class="ss">specified: </span><span class="sr">/?/</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/RegexpError.html">RegexpError Reference</a></p>

<h3 id="runtimeerror">RuntimeError</h3>

<p>A generic error class raised when an invalid operation is attempted.
Kernel#raise will raise a RuntimeError if no Exception class is
specified.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">raise</span> <span class="s2">"ouch"</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">RuntimeError</span><span class="p">:</span> <span class="n">ouch</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/RuntimeError.html">RuntimeError
Reference</a></p>

<h4 id="frozenerror">FrozenError</h4>

<p>Raised when there is an attempt to modify a frozen object.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">].</span><span class="nf">freeze</span> <span class="o">&lt;&lt;</span> <span class="mi">4</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">FrozenError</span><span class="p">:</span> <span class="n">can</span><span class="err">'</span><span class="n">t</span> <span class="n">modify</span> <span class="n">frozen</span> <span class="no">Array</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/FrozenError.html">FrozenError Reference</a></p>

<h3 id="systemcallerror">SystemCallError</h3>

<p>SystemCallError is the base class for all low-level platform-dependent
errors.</p>

<p>The errors available on the current platform are subclasses of
SystemCallError and are defined in the Errno module.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">File</span><span class="p">.</span><span class="nf">open</span><span class="p">(</span><span class="s2">"does/not/exist"</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Errno</span><span class="o">::</span><span class="no">ENOENT</span><span class="p">:</span> <span class="no">No</span> <span class="n">such</span> <span class="n">file</span> <span class="n">or</span> <span class="n">directory</span> <span class="o">-</span> <span class="n">does</span><span class="o">/</span><span class="n">not</span><span class="o">/</span><span class="n">exist</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/SystemCallError.html">SystemCallError
Reference</a></p>

<h4 id="errno">Errno</h4>

<p>Ruby exception objects are subclasses of <code class="highlighter-rouge">Exception</code>. However, operating
systems typically report errors using plain integers. Module <code class="highlighter-rouge">Errno</code> is
created dynamically to map these operating system errors to Ruby
classes, with each error number generating its own subclass of
<code class="highlighter-rouge">SystemCallError</code>. As the subclass is created in module <code class="highlighter-rouge">Errno</code>, its
name will start <code class="highlighter-rouge">Errno::</code>.</p>

<p>The names of the <code class="highlighter-rouge">Errno::</code> classes depend on the environment in which
Ruby runs. On a typical Unix or Windows platform, there are <code class="highlighter-rouge">Errno</code>
classes such as <code class="highlighter-rouge">Errno::EACCES</code>, <code class="highlighter-rouge">Errno::EAGAIN</code>, <code class="highlighter-rouge">Errno::EINTR</code>, and so
on.</p>

<p>The integer operating system error number corresponding to a particular
error is available as the class constant <code class="highlighter-rouge">Errno::</code><em>error</em><code class="highlighter-rouge">::Errno</code>.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Errno</span><span class="o">::</span><span class="no">EACCES</span><span class="o">::</span><span class="no">Errno</span>   <span class="c1">#=&gt; 13</span>
<span class="no">Errno</span><span class="o">::</span><span class="no">EAGAIN</span><span class="o">::</span><span class="no">Errno</span>   <span class="c1">#=&gt; 11</span>
<span class="no">Errno</span><span class="o">::</span><span class="no">EINTR</span><span class="o">::</span><span class="no">Errno</span>    <span class="c1">#=&gt; 4</span>
</code></pre></div></div>

<p>The full list of operating system errors on your particular platform are
available as the constants of <code class="highlighter-rouge">Errno</code>.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Errno</span><span class="p">.</span><span class="nf">constants</span>   <span class="c1">#=&gt; :E2BIG, :EACCES, :EADDRINUSE, :EADDRNOTAVAIL, ...</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/Errno.html">Errno Reference</a></p>

<h3 id="threaderror">ThreadError</h3>

<p>Raised when an invalid operation is attempted on a thread.</p>

<p>For example, when no other thread has been started:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">Thread</span><span class="p">.</span><span class="nf">stop</span>
</code></pre></div></div>

<p>This will raises the following exception:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">ThreadError</span><span class="p">:</span> <span class="n">stopping</span> <span class="n">only</span> <span class="n">thread</span>
<span class="ss">note: </span><span class="n">use</span> <span class="nb">sleep</span> <span class="n">to</span> <span class="n">stop</span> <span class="n">forever</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/ThreadError.html">ThreadError Reference</a></p>

<h3 id="typeerror">TypeError</h3>

<p>Raised when encountering an object that is not of the expected type.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="p">[</span><span class="mi">1</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">].</span><span class="nf">first</span><span class="p">(</span><span class="s2">"two"</span><span class="p">)</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">TypeError</span><span class="p">:</span> <span class="n">no</span> <span class="n">implicit</span> <span class="n">conversion</span> <span class="n">of</span> <span class="no">String</span> <span class="n">into</span> <span class="no">Integer</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/TypeError.html">TypeError Reference</a></p>

<h3 id="zerodivisionerror">ZeroDivisionError</h3>

<p>Raised when attempting to divide an integer by 0.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="mi">42</span> <span class="o">/</span> <span class="mi">0</span>   <span class="c1">#=&gt; ZeroDivisionError: divided by 0</span>
</code></pre></div></div>

<p>Note that only division by an exact 0 will raise the exception:</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="mi">42</span> <span class="o">/</span>  <span class="mf">0.0</span>   <span class="c1">#=&gt; Float::INFINITY</span>
<span class="mi">42</span> <span class="o">/</span> <span class="o">-</span><span class="mf">0.0</span>   <span class="c1">#=&gt; -Float::INFINITY</span>
<span class="mi">0</span>  <span class="o">/</span>  <span class="mf">0.0</span>   <span class="c1">#=&gt; NaN</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/ZeroDivisionError.html">ZeroDivisionError
Reference</a></p>

<h2 id="systemexit">SystemExit</h2>

<p>Raised by <code class="highlighter-rouge">exit</code> to initiate the termination of the script.</p>

<p><a href="http://ruby-doc.org/core-2.5.0/SystemExit.html">SystemExit Reference</a></p>

<h2 id="systemstackerror">SystemStackError</h2>

<p>Raised in case of a stack overflow.</p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">def</span> <span class="nf">me_myself_and_i</span>
  <span class="n">me_myself_and_i</span>
<span class="k">end</span>
<span class="n">me_myself_and_i</span>
</code></pre></div></div>

<p><em>raises the exception:</em></p>

<div class="language-ruby highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="no">SystemStackError</span><span class="p">:</span> <span class="n">stack</span> <span class="n">level</span> <span class="n">too</span> <span class="n">deep</span>
</code></pre></div></div>

<p><a href="http://ruby-doc.org/core-2.5.0/SystemStackError.html">SystemStackError
Reference</a></p>

<h2 id="fatal">fatal</h2>

<p>fatal is an Exception that is raised when Ruby has encountered a fatal
error and must exit. You are not able to rescue fatal.</p>

<p><a href="http://ruby-doc.org/core-2.5.0/fatal.html">fatal Reference</a></p>



                <!-- Mobile navigation buttons -->


                <!--
                    <a href="cli/cli-tool.html" class="mobile-nav-chapters next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                 -->

            </div>



               <!--
                <a href="cli/cli-tool.html" class="nav-chapters next" title="You can navigate through the chapters using the arrow keys">
                    <i class="fa fa-angle-right"></i>
                </a>
                 -->

        </div>


        <script src="js/book.js"></script>
    </body>
</html>
